home/urls.py
from django.urls import path
from . import views

app_name = 'site_home'
urlpatterns = [
    path('', views.home, name='index'),
    path('docs/', views.docs, name='docs'),
]

own_custom_app/urls.py

# from django.contrib import admin
from django.urls import path, include
from . import api_v1

urlpatterns = [
    # path('admin/', admin.site.urls),            # remove this in prod
    path('', include('home.urls', namespace='home')),
    path('user/', include('user.urls', namespace='user')),
    path('api/v1/', include(api_v1, namespace='api_v1')),
    path('proxy/', include('proxy.urls', namespace='proxy')),
]

home/views.py
from django.shortcuts import render

def home(request):
    return render(request, 'home/home.html')

def docs(request):
    return render(request, 'home/docs.html')

home/templates/home/docs.html
<!doctype html>
<html>
  <head>
    <title>Tech News - OpenAPI 3.0</title>
    <style type="text/css">
      body {
      	font-family: Trebuchet MS, sans-serif;
      	font-size: 15px;
      	color: #444;
      	margin-right: 24px;
      }
      
      h1	{
      	font-size: 25px;
      }
      h2	{
      	font-size: 20px;
      }
      h3	{
      	font-size: 16px;
      	font-weight: bold;
      }
      hr	{
      	height: 1px;
      	border: 0;
      	color: #ddd;
      	background-color: #ddd;
      }
      
      .app-desc {
        clear: both;
        margin-left: 20px;
      }
      .param-name {
        width: 100%;
      }
      .license-info {
        margin-left: 20px;
      }
      
      .license-url {
        margin-left: 20px;
      }
      
      .model {
        margin: 0 0 0px 20px;
      }
      
      .method {
        margin-left: 20px;
      }
      
      .method-notes	{
      	margin: 10px 0 20px 0;
      	font-size: 90%;
      	color: #555;
      }
      
      pre {
        padding: 10px;
        margin-bottom: 2px;
      }
      
      .http-method {
       text-transform: uppercase;
      }
      
      pre.get {
        background-color: #0f6ab4;
      }
      
      pre.post {
        background-color: #10a54a;
      }
      
      pre.put {
        background-color: #c5862b;
      }
      
      pre.delete {
        background-color: #a41e22;
      }
      
      .huge	{
      	color: #fff;
      }
      
      pre.example {
        background-color: #f3f3f3;
        padding: 10px;
        border: 1px solid #ddd;
      }
      
      code {
        white-space: pre;
      }
      
      .nickname {
        font-weight: bold;
      }
      
      .method-path {
        font-size: 1.5em;
        background-color: #0f6ab4;
      }
      
      .up {
        float:right;
      }
      
      .parameter {
        width: 500px;
      }
      
      .param {
        width: 500px;
        padding: 10px 0 0 20px;
        font-weight: bold;
      }
      
      .param-desc {
        width: 700px;
        padding: 0 0 0 20px;
        color: #777;
      }
      
      .param-type {
        font-style: italic;
      }
      
      .param-enum-header {
      width: 700px;
      padding: 0 0 0 60px;
      color: #777;
      font-weight: bold;
      }
      
      .param-enum {
      width: 700px;
      padding: 0 0 0 80px;
      color: #777;
      font-style: italic;
      }
      
      .field-label {
        padding: 0;
        margin: 0;
        clear: both;
      }
      
      .field-items	{
      	padding: 0 0 15px 0;
      	margin-bottom: 15px;
      }
      
      .return-type {
        clear: both;
        padding-bottom: 10px;
      }
      
      .param-header {
        font-weight: bold;
      }
      
      .method-tags {
        text-align: right;
      }
      
      .method-tag {
        background: none repeat scroll 0% 0% #24A600;
        border-radius: 3px;
        padding: 2px 10px;
        margin: 2px;
        color: #FFF;
        display: inline-block;
        text-decoration: none;
      }
    </style>
  </head>
  <body>
  <h1>Tech News - OpenAPI 3.0</h1>
    <div class="app-desc">OpenAPI v3 based documentation for fetching latest technology URLs.
These urls are fetched from popular domains like xda-developers which consists of news focusing mainly on the mobile side of tech.</div>
    
    <div class="license-info">Apache 2.0</div>
    <div class="license-url">http://www.apache.org/licenses/LICENSE-2.0.html</div>
  <h2>Access</h2>

  <h2><a name="__Methods">Methods</a></h2>

  <h3>Table of Contents </h3>
  <div class="method-summary"></div>
  <h4><a href="#Store">Store</a></h4>
  <ul>
  <li><a href="#getArticles"><code><span class="http-method">get</span> /api/v1/tech/feeds/xda/</code></a></li>
  </ul>

  <h1><a name="Store">Store</a></h1>
  <div class="method"><a name="getArticles"></a>
    <div class="method-path">
    <a class="up" href="#__Methods">Up</a>
    <pre class="get"><code class="huge"><span class="http-method">get</span> /api/v1/tech/feeds/xda/</code></pre></div>
    <div class="method-summary">Returns latest news article urls (<span class="nickname">getArticles</span>)</div>
    <div class="method-notes">URLs to xda-developer recent articles</div>







    <h3 class="field-label">Return type</h3>
    <div class="return-type">
      array[<a href="#Feed">Feed</a>]
      
    </div>

    <!--Todo: process Response Object and its headers, schema, examples -->

    <h3 class="field-label">Example data</h3>
    <div class="example-data-content-type">Content-Type: application/json</div>
    <pre class="example"><code>[ "", "" ]</code></pre>

    <h3 class="field-label">Produces</h3>
    This API call produces the following media types according to the <span class="header">Accept</span> request header;
    the media type will be conveyed by the <span class="header">Content-Type</span> response header.
    <ul>
      <li><code>application/json</code></li>
    </ul>

    <h3 class="field-label">Responses</h3>
    <h4 class="field-label">200</h4>
    successful operation
        
  </div> <!-- method -->
  <hr/>

  <h2><a name="__Models">Models</a></h2>

  <div class="model">
    <h3><a name="Feed"><code>Feed</code></a> <a class="up" href="#__Models">Up</a></h3>
    
    <div class="field-items">
          </div>  <!-- field-items -->
  </div>
  </body>
</html>

home/templates/home/home.html
{% extends 'base.html' %}

{% block title %}
    Home
{% endblock title %}

{% block inline_css %}
  <style>
    .tab-1 {
      margin-left: 1rem;
    }
    .tab-2 {
      margin-left: 2rem;
    }
    .tab-3 {
      margin-left: 3rem;
    }
    
    
  </style>
{% endblock inline_css %}


{% block content %}
<div class="tab-1">
  
  <header class="tab-2">
    <h1>Endpoints</h1>
    <section class="">
      <h1>Base Endpoint</h1>
      {% url 'api_v1:index' as base_path %}
      <pre>{{ request.get_host }}{{ base_path }}</pre>
      <p>To authenticate, include api key in below format.</p>
      <p>Include the api key in Authorization Header like below: (test key provided)</p>
      <pre>{'Authorization': 'Basic ' + '96a768f388be5aaa8416c361570d053611357724f1b9'}</pre>
    </section>
  </header>

  <section class="tab-2">
    <h2>Endpoints for technology news</h1>
    {% comment %}use variable to capture url so that its evaluated first{% endcomment %}
    {% url 'api_v1:tech_news:feeds:index' as feed_url %}
    <pre>/{{ feed_url|cut:base_path }}</pre>
    <div class="tab-3">
      <h3>Xda Developers</h3>
      {% url 'api_v1:tech_news:feeds:xda' as xda_url %}
      <pre>/{{ xda_url|cut:feed_url }}</pre>
      <p>Example reponse</p>
      <pre>[
        "https://www.xda-developers.com/oneplus-9-pro-vs-galaxy-s21-ultra/",
        "https://www.xda-developers.com/xiaomi-premium-android-tablets-nabu-elish-enuma/",
        "https://www.xda-developers.com/third-party-launchers-animation-pixel-phones/",
        "https://www.xda-developers.com/how-to-change-boot-animation-charging-screen-miui-xiaomi/",
        "https://www.xda-developers.com/youtube-show-video-titles-native-language/"
      ]
      </pre>

      <h3>Torrent freak</h3>
      {% url 'api_v1:tech_news:feeds:torrentfreak' as tf_url %}
      <pre>/{{ tf_url|cut:feed_url }}</pre>

    </div>
    
  </section>
    
</div>
{% endblock content %}